openapi: 3.0.0
info:
  version: 1.0.0
  title: Integrate with JobPays
  description: >-
    Power your organization with a more secured and user friendly API that
    support all form of transaction and process within your organization and
    outside your organization.
servers:
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/BARIDULE/Jobpays/1.0.0
security:
  - implicit:
      - read
      - write
tags:
  - name: business
    description: Everything about getting your business on JobPays.
    externalDocs:
      description: Find out here
      url: https://integration.jobpays.app
  - name: kyc
    description: Conduct your business KYC.
    externalDocs:
      description: Check here
      url: http://integration.jobpays.app
  - name: account
    description: Generating EU bank account.
    externalDocs:
      description: Follow through
      url: http://integration.jobpays.app
  - name: transfer
    description: Perform internal fund transfer as an organization.
    externalDocs:
      description: Read here
      url: http://integration.jobpays.app
  - name: recieve
    description: Accepting funds transfer from other bank account.
    externalDocs:
      description: Find out here
      url: http://integration.jobpays.app
  - name: balance
    description: Check account balance.
    externalDocs:
      description: Check here
      url: http://integration.jobpays.app
  - name: card
    description: Generating a debit card.
    externalDocs:
      description: Follow through
      url: http://integration.jobpays.app
  - name: freeze
    description: Freeze debit card.
    externalDocs:
      description: Read here
      url: http://integration.jobpays.app
  - name: block
    description: Blocking of debit card.
    externalDocs:
      description: Find out here
      url: http://integration.jobpays.app
paths:
  /business:
    $ref: paths/business.yaml
  /business/{businessId}/uploadImage:
    $ref: paths/business_{businessId}_uploadImage.yaml
  /kyc:
    $ref: paths/kyc.yaml
  /account:
    $ref: paths/account.yaml
  /account/transfer:
    $ref: paths/account_transfer.yaml
  /account/recieve:
    $ref: paths/account_recieve.yaml
  /account/balance:
    $ref: paths/account_balance.yaml
  /account/currency:
    $ref: paths/account_currency.yaml
  /card:
    $ref: paths/card.yaml
  /card/freeze:
    $ref: paths/card_freeze.yaml
  /Card/block:
    $ref: paths/Card_block.yaml
components:
  securitySchemes:
    implicit:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: http://example.com/oauth/auth
          scopes:
            write: allows modifying resources
            read: allows reading resources
